name: "Publish Wasm component"
description: "Build a WebAssembly component using wash and output the artifact path"

# Workflows using this action will need the following permissions:
# permissions:
#   contents: write
#   packages: write
#   attestations: write
#   id-token: write

inputs:
  registry:
    description: "Container registry to push to"
    required: false
    default: "ghcr.io"
  component_path:
    description: "Path to the built WebAssembly component"
    required: true
  attestation:
    description: "Whether to generate an attestation for the published artifact"
    required: false
    default: "false"
  image_tags:
    description: "Additional tags to apply to the published image, comma-separated"
    required: false
    default: ${{ github.ref_name }}
  token:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}
  cyclonedx-version:
    description: "Version of CycloneDX CLI to use"
    required: false
    default: "0.29.1"

runs:
  using: "composite"
  steps:
    - name: Login to container registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Set image name and SBOM filename
      id: image-info
      shell: bash
      run: |
        echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
        echo "sbom_filename=$(echo "${GITHUB_REPOSITORY,,}" | tr '/' '-').spdx.json" >> $GITHUB_OUTPUT

    - name: Push Wasm component to container registry
      id: push
      shell: bash
      env:
        IMAGE_TAGS: ${{ inputs.image_tags }}
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ steps.image-info.outputs.image_name }}
        COMPONENT_PATH: ${{ inputs.component_path }}
      run: |
        # Split comma-separated tags and push each one
        IFS=',' read -ra TAGS <<< "$IMAGE_TAGS"

        digests=()
        for tag in "${TAGS[@]}"; do
          # Trim whitespace
          tag=$(echo "$tag" | xargs)
          echo "Pushing $REGISTRY/$IMAGE_NAME:$tag"

          push_output=$(wash oci push --output json "$REGISTRY/$IMAGE_NAME:$tag" "$COMPONENT_PATH")
          digest=$(echo "$push_output" | jq -r .data.digest)

          if [ -z "$digest" ] || [ "$digest" = "null" ]; then
            echo "Failed to determine pushed component digest for tag $tag: $push_output" >&2
            exit 1
          fi

          echo "Component pushed with digest: $digest for tag: $tag"
          digests+=("$digest")
        done

        # Use the first digest for attestation (all pushes of the same content have the same digest)
        echo "digest=${digests[0]}" >> $GITHUB_OUTPUT
        echo "all_digests=$(IFS=,; echo "${digests[*]}")" >> $GITHUB_OUTPUT

    - name: Generate artifact attestation
      if: ${{ inputs.attestation == 'true' }}
      uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3.2.0
      with:
        subject-name: ${{ inputs.registry }}/${{ steps.image-info.outputs.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - uses: taiki-e/install-action@1cf3de8de323df92fe08c793e53eaef58799aec4 # v2.68.3
      if: ${{ inputs.attestation == 'true' }}
      with:
        tool: auditable2cdx

    - name: Install CycloneDX CLI
      if: ${{ inputs.attestation == 'true' }}
      shell: bash
      env:
        CYCLONEDX_VERSION: ${{ inputs.cyclonedx-version }}
      run: |
        # Detect OS and architecture for cyclonedx-cli binary
        case "$(uname -s)" in
          Linux*)
            case "$(uname -m)" in
              x86_64) BINARY_NAME="cyclonedx-linux-x64" ;;
              aarch64|arm64) BINARY_NAME="cyclonedx-linux-arm64" ;;
              armv7l|armv6l) BINARY_NAME="cyclonedx-linux-arm" ;;
              *) echo "Unsupported Linux architecture: $(uname -m)"; exit 1 ;;
            esac
            ;;
          Darwin*)
            case "$(uname -m)" in
              x86_64) BINARY_NAME="cyclonedx-osx-x64" ;;
              arm64) BINARY_NAME="cyclonedx-osx-arm64" ;;
              *) echo "Unsupported macOS architecture: $(uname -m)"; exit 1 ;;
            esac
            ;;
          CYGWIN*|MINGW*|MSYS*)
            case "$(uname -m)" in
              x86_64) BINARY_NAME="cyclonedx-win-x64.exe" ;;
              aarch64|arm64) BINARY_NAME="cyclonedx-win-arm64.exe" ;;
              i686) BINARY_NAME="cyclonedx-win-x86.exe" ;;
              *) echo "Unsupported Windows architecture: $(uname -m)"; exit 1 ;;
            esac
            ;;
          *) echo "Unsupported OS: $(uname -s)"; exit 1 ;;
        esac

        # Pin to known good version
        echo "Downloading cyclonedx-cli binary: $BINARY_NAME"
        curl -LO "https://github.com/CycloneDX/cyclonedx-cli/releases/download/v${CYCLONEDX_VERSION}/${BINARY_NAME}"
        chmod +x "$BINARY_NAME"

        # Create a directory for the binary and add to PATH
        mkdir -p "$HOME/.local/bin"
        mv "$BINARY_NAME" "$HOME/.local/bin/cyclonedx"
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Extract SBOM from component
      id: extract-sbom
      if: ${{ inputs.attestation == 'true' }}
      shell: bash
      env:
        COMPONENT_PATH: ${{ inputs.component_path }}
      run: |
        # Create absolute path for CycloneDX SBOM file
        CYCLONEDX_PATH="$(pwd)/$(echo "${GITHUB_REPOSITORY,,}" | tr '/' '-').cyclonedx.json"

        # Extract CycloneDX SBOM
        auditable2cdx "$COMPONENT_PATH" > "$CYCLONEDX_PATH"
        echo "CycloneDX SBOM created at: $CYCLONEDX_PATH"

        echo "cyclonedx_path=$CYCLONEDX_PATH" >> $GITHUB_OUTPUT

    - name: Convert SBOM to SPDX
      id: convert-sbom
      if: ${{ inputs.attestation == 'true' }}
      shell: bash
      env:
        SBOM_FILENAME: ${{ steps.image-info.outputs.sbom_filename }}
        CYCLONEDX_ABS_PATH: ${{ steps.extract-sbom.outputs.cyclonedx_path }}
      run: |
        # Create absolute path for SPDX SBOM file
        SBOM_PATH="$(pwd)/$SBOM_FILENAME"

        # Convert CycloneDX to SPDX format for GitHub attestation
        cyclonedx convert --input-file "$CYCLONEDX_ABS_PATH" --output-file "$SBOM_PATH" --output-format spdxjson

        echo "sbom_abs_path=$SBOM_PATH" >> $GITHUB_OUTPUT

        # Debug: Print SBOM file info and contents
        echo "SPDX SBOM file created at: $SBOM_PATH"
        echo "SPDX SBOM file size: $(wc -c < "$SBOM_PATH") bytes"
        echo "SPDX SBOM file first 20 lines:"
        head -20 "$SBOM_PATH"
        echo "SPDX SBOM file format detection:"
        file "$SBOM_PATH"

    - uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
      if: ${{ inputs.attestation == 'true' }}
      with:
        subject-name: ${{ inputs.registry }}/${{ steps.image-info.outputs.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        sbom-path: ${{ steps.convert-sbom.outputs.sbom_abs_path }}
