name: "Setup Cargo Auditable for wash builds"
description: |
  Configures a rust toolchain with cargo-auditable for use in building
  WebAssembly components with wash and creating an auditable SBOM.

  wash CLI must be installed and available in PATH. We recommend using the
  wasmcloud/setup-wash-action prior to this action to install wash.

inputs:
  working-directory:
    description: "Directory containing the WebAssembly project"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@1cf3de8de323df92fe08c793e53eaef58799aec4 # v2.68.3
      with:
        tool: cargo-auditable,cargo-audit

    - name: Set auditable as custom build command in .wash/config.json
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p .wash

        # Create or update config with jq, merging with existing config
        if [ -f .wash/config.json ]; then
          # Merge with existing config, ensuring nested objects exist
          jq '(.build // {}) as $build | 
              (.build.rust // {}) as $rust |
              .build = ($build | .rust = ($rust | 
                .custom_command = ["cargo", "auditable", "build", "--release", "--target", "wasm32-wasip2", "--message-format", "json"] |
                .target = "wasm32-wasip2" |
                .release = true
              ))' .wash/config.json > .wash/config.json.tmp
          mv .wash/config.json.tmp .wash/config.json
        else
          # Create new config
          jq -n '{
            "build": {
              "rust": {
                "target": "wasm32-wasip2",
                "release": true,
                "custom_command": ["cargo", "auditable", "build", "--release", "--target", "wasm32-wasip2", "--message-format", "json"]
              }
            }
          }' > .wash/config.json
        fi
