name: "Setup Cargo Auditable for wash builds"
description: |
  Configures a rust toolchain with cargo-auditable for use in building
  WebAssembly components with wash and creating an auditable SBOM.

  wash CLI must be installed and available in PATH. We recommend using the
  wasmcloud/setup-wash-action prior to this action to install wash.

  A Cargo project (Cargo.toml) must already exist in the working directory
  before calling this action, as it reads the package name to determine
  the component output path.

inputs:
  working-directory:
    description: "Directory containing the WebAssembly project"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@1cf3de8de323df92fe08c793e53eaef58799aec4 # v2.68.3
      with:
        tool: cargo-auditable,cargo-audit

    - name: Set auditable as custom build command in .wash/config.yaml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        # Derive the wasm artifact path from the Cargo package name
        PACKAGE_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name' | tr '-' '_')
        COMPONENT_PATH="target/wasm32-wasip2/release/${PACKAGE_NAME}.wasm"

        mkdir -p .wash

        # Write .wash/config.yaml in wash v2.0 format
        printf 'build:\n  command: cargo auditable build --release --target wasm32-wasip2\n  component_path: "%s"\n' \
          "$COMPONENT_PATH" > .wash/config.yaml
